### YamlMime:ManagedReference
items:
- uid: LiveKit.Proto.ClientConfigSetting
  commentId: T:LiveKit.Proto.ClientConfigSetting
  id: ClientConfigSetting
  parent: LiveKit.Proto
  children:
  - LiveKit.Proto.ClientConfigSetting.Disabled
  - LiveKit.Proto.ClientConfigSetting.Enabled
  - LiveKit.Proto.ClientConfigSetting.Unset
  langs:
  - csharp
  - vb
  name: ClientConfigSetting
  nameWithType: ClientConfigSetting
  fullName: LiveKit.Proto.ClientConfigSetting
  type: Enum
  source:
    remote:
      path: LiveKit.AspNetCore.ServerSdk.Abstractions/Proto/LivekitModels.cs
      branch: main
      repo: git@github.com:ahmedisam99/livekit-server-sdk-aspnetcore.git
    id: ClientConfigSetting
    path: ../LiveKit.AspNetCore.ServerSdk.Abstractions/Proto/LivekitModels.cs
    startLine: 409
  assemblies:
  - LiveKit.AspNetCore.ServerSdk.Abstractions
  namespace: LiveKit.Proto
  syntax:
    content: public enum ClientConfigSetting
    content.vb: Public Enum ClientConfigSetting
- uid: LiveKit.Proto.ClientConfigSetting.Unset
  commentId: F:LiveKit.Proto.ClientConfigSetting.Unset
  id: Unset
  parent: LiveKit.Proto.ClientConfigSetting
  langs:
  - csharp
  - vb
  name: Unset
  nameWithType: ClientConfigSetting.Unset
  fullName: LiveKit.Proto.ClientConfigSetting.Unset
  type: Field
  source:
    remote:
      path: LiveKit.AspNetCore.ServerSdk.Abstractions/Proto/LivekitModels.cs
      branch: main
      repo: git@github.com:ahmedisam99/livekit-server-sdk-aspnetcore.git
    id: Unset
    path: ../LiveKit.AspNetCore.ServerSdk.Abstractions/Proto/LivekitModels.cs
    startLine: 410
  assemblies:
  - LiveKit.AspNetCore.ServerSdk.Abstractions
  namespace: LiveKit.Proto
  syntax:
    content: >-
      [OriginalName("UNSET")]

      Unset = 0
    return:
      type: LiveKit.Proto.ClientConfigSetting
    content.vb: >-
      <OriginalName("UNSET")>

      Unset = 0
  attributes:
  - type: Google.Protobuf.Reflection.OriginalNameAttribute
    ctor: Google.Protobuf.Reflection.OriginalNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: UNSET
- uid: LiveKit.Proto.ClientConfigSetting.Disabled
  commentId: F:LiveKit.Proto.ClientConfigSetting.Disabled
  id: Disabled
  parent: LiveKit.Proto.ClientConfigSetting
  langs:
  - csharp
  - vb
  name: Disabled
  nameWithType: ClientConfigSetting.Disabled
  fullName: LiveKit.Proto.ClientConfigSetting.Disabled
  type: Field
  source:
    remote:
      path: LiveKit.AspNetCore.ServerSdk.Abstractions/Proto/LivekitModels.cs
      branch: main
      repo: git@github.com:ahmedisam99/livekit-server-sdk-aspnetcore.git
    id: Disabled
    path: ../LiveKit.AspNetCore.ServerSdk.Abstractions/Proto/LivekitModels.cs
    startLine: 411
  assemblies:
  - LiveKit.AspNetCore.ServerSdk.Abstractions
  namespace: LiveKit.Proto
  syntax:
    content: >-
      [OriginalName("DISABLED")]

      Disabled = 1
    return:
      type: LiveKit.Proto.ClientConfigSetting
    content.vb: >-
      <OriginalName("DISABLED")>

      Disabled = 1
  attributes:
  - type: Google.Protobuf.Reflection.OriginalNameAttribute
    ctor: Google.Protobuf.Reflection.OriginalNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: DISABLED
- uid: LiveKit.Proto.ClientConfigSetting.Enabled
  commentId: F:LiveKit.Proto.ClientConfigSetting.Enabled
  id: Enabled
  parent: LiveKit.Proto.ClientConfigSetting
  langs:
  - csharp
  - vb
  name: Enabled
  nameWithType: ClientConfigSetting.Enabled
  fullName: LiveKit.Proto.ClientConfigSetting.Enabled
  type: Field
  source:
    remote:
      path: LiveKit.AspNetCore.ServerSdk.Abstractions/Proto/LivekitModels.cs
      branch: main
      repo: git@github.com:ahmedisam99/livekit-server-sdk-aspnetcore.git
    id: Enabled
    path: ../LiveKit.AspNetCore.ServerSdk.Abstractions/Proto/LivekitModels.cs
    startLine: 412
  assemblies:
  - LiveKit.AspNetCore.ServerSdk.Abstractions
  namespace: LiveKit.Proto
  syntax:
    content: >-
      [OriginalName("ENABLED")]

      Enabled = 2
    return:
      type: LiveKit.Proto.ClientConfigSetting
    content.vb: >-
      <OriginalName("ENABLED")>

      Enabled = 2
  attributes:
  - type: Google.Protobuf.Reflection.OriginalNameAttribute
    ctor: Google.Protobuf.Reflection.OriginalNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: ENABLED
references:
- uid: LiveKit.Proto
  commentId: N:LiveKit.Proto
  href: LiveKit.html
  name: LiveKit.Proto
  nameWithType: LiveKit.Proto
  fullName: LiveKit.Proto
  spec.csharp:
  - uid: LiveKit
    name: LiveKit
    href: LiveKit.html
  - name: .
  - uid: LiveKit.Proto
    name: Proto
    href: LiveKit.Proto.html
  spec.vb:
  - uid: LiveKit
    name: LiveKit
    href: LiveKit.html
  - name: .
  - uid: LiveKit.Proto
    name: Proto
    href: LiveKit.Proto.html
- uid: LiveKit.Proto.ClientConfigSetting
  commentId: T:LiveKit.Proto.ClientConfigSetting
  parent: LiveKit.Proto
  href: LiveKit.Proto.ClientConfigSetting.html
  name: ClientConfigSetting
  nameWithType: ClientConfigSetting
  fullName: LiveKit.Proto.ClientConfigSetting
