### YamlMime:ManagedReference
items:
- uid: LiveKit.Proto.IngressAudioEncodingPreset
  commentId: T:LiveKit.Proto.IngressAudioEncodingPreset
  id: IngressAudioEncodingPreset
  parent: LiveKit.Proto
  children:
  - LiveKit.Proto.IngressAudioEncodingPreset.OpusMono64Kbs
  - LiveKit.Proto.IngressAudioEncodingPreset.OpusStereo96Kbps
  langs:
  - csharp
  - vb
  name: IngressAudioEncodingPreset
  nameWithType: IngressAudioEncodingPreset
  fullName: LiveKit.Proto.IngressAudioEncodingPreset
  type: Enum
  source:
    remote:
      path: LiveKit.AspNetCore.ServerSdk.Abstractions/Proto/LivekitIngress.cs
      branch: main
      repo: git@github.com:ahmedisam99/livekit-server-sdk-aspnetcore.git
    id: IngressAudioEncodingPreset
    path: ../LiveKit.AspNetCore.ServerSdk.Abstractions/Proto/LivekitIngress.cs
    startLine: 141
  assemblies:
  - LiveKit.AspNetCore.ServerSdk.Abstractions
  namespace: LiveKit.Proto
  syntax:
    content: public enum IngressAudioEncodingPreset
    content.vb: Public Enum IngressAudioEncodingPreset
- uid: LiveKit.Proto.IngressAudioEncodingPreset.OpusStereo96Kbps
  commentId: F:LiveKit.Proto.IngressAudioEncodingPreset.OpusStereo96Kbps
  id: OpusStereo96Kbps
  parent: LiveKit.Proto.IngressAudioEncodingPreset
  langs:
  - csharp
  - vb
  name: OpusStereo96Kbps
  nameWithType: IngressAudioEncodingPreset.OpusStereo96Kbps
  fullName: LiveKit.Proto.IngressAudioEncodingPreset.OpusStereo96Kbps
  type: Field
  source:
    remote:
      path: LiveKit.AspNetCore.ServerSdk.Abstractions/Proto/LivekitIngress.cs
      branch: main
      repo: git@github.com:ahmedisam99/livekit-server-sdk-aspnetcore.git
    id: OpusStereo96Kbps
    path: ../LiveKit.AspNetCore.ServerSdk.Abstractions/Proto/LivekitIngress.cs
    startLine: 145
  assemblies:
  - LiveKit.AspNetCore.ServerSdk.Abstractions
  namespace: LiveKit.Proto
  summary: OPUS, 2 channels, 96kbps
  example: []
  syntax:
    content: >-
      [OriginalName("OPUS_STEREO_96KBPS")]

      OpusStereo96Kbps = 0
    return:
      type: LiveKit.Proto.IngressAudioEncodingPreset
    content.vb: >-
      <OriginalName("OPUS_STEREO_96KBPS")>

      OpusStereo96Kbps = 0
  attributes:
  - type: Google.Protobuf.Reflection.OriginalNameAttribute
    ctor: Google.Protobuf.Reflection.OriginalNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: OPUS_STEREO_96KBPS
- uid: LiveKit.Proto.IngressAudioEncodingPreset.OpusMono64Kbs
  commentId: F:LiveKit.Proto.IngressAudioEncodingPreset.OpusMono64Kbs
  id: OpusMono64Kbs
  parent: LiveKit.Proto.IngressAudioEncodingPreset
  langs:
  - csharp
  - vb
  name: OpusMono64Kbs
  nameWithType: IngressAudioEncodingPreset.OpusMono64Kbs
  fullName: LiveKit.Proto.IngressAudioEncodingPreset.OpusMono64Kbs
  type: Field
  source:
    remote:
      path: LiveKit.AspNetCore.ServerSdk.Abstractions/Proto/LivekitIngress.cs
      branch: main
      repo: git@github.com:ahmedisam99/livekit-server-sdk-aspnetcore.git
    id: OpusMono64Kbs
    path: ../LiveKit.AspNetCore.ServerSdk.Abstractions/Proto/LivekitIngress.cs
    startLine: 149
  assemblies:
  - LiveKit.AspNetCore.ServerSdk.Abstractions
  namespace: LiveKit.Proto
  summary: OPUS, 1 channel, 64kbps
  example: []
  syntax:
    content: >-
      [OriginalName("OPUS_MONO_64KBS")]

      OpusMono64Kbs = 1
    return:
      type: LiveKit.Proto.IngressAudioEncodingPreset
    content.vb: >-
      <OriginalName("OPUS_MONO_64KBS")>

      OpusMono64Kbs = 1
  attributes:
  - type: Google.Protobuf.Reflection.OriginalNameAttribute
    ctor: Google.Protobuf.Reflection.OriginalNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: OPUS_MONO_64KBS
references:
- uid: LiveKit.Proto
  commentId: N:LiveKit.Proto
  href: LiveKit.html
  name: LiveKit.Proto
  nameWithType: LiveKit.Proto
  fullName: LiveKit.Proto
  spec.csharp:
  - uid: LiveKit
    name: LiveKit
    href: LiveKit.html
  - name: .
  - uid: LiveKit.Proto
    name: Proto
    href: LiveKit.Proto.html
  spec.vb:
  - uid: LiveKit
    name: LiveKit
    href: LiveKit.html
  - name: .
  - uid: LiveKit.Proto
    name: Proto
    href: LiveKit.Proto.html
- uid: LiveKit.Proto.IngressAudioEncodingPreset
  commentId: T:LiveKit.Proto.IngressAudioEncodingPreset
  parent: LiveKit.Proto
  href: LiveKit.Proto.IngressAudioEncodingPreset.html
  name: IngressAudioEncodingPreset
  nameWithType: IngressAudioEncodingPreset
  fullName: LiveKit.Proto.IngressAudioEncodingPreset
