// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: livekit_connector.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LiveKit.Proto {

  /// <summary>Holder for reflection information generated from livekit_connector.proto</summary>
  public static partial class LivekitConnectorReflection {

    #region Descriptor
    /// <summary>File descriptor for livekit_connector.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LivekitConnectorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdsaXZla2l0X2Nvbm5lY3Rvci5wcm90bxIHbGl2ZWtpdBogbGl2ZWtpdF9j",
            "b25uZWN0b3Jfd2hhdHNhcHAucHJvdG8aHmxpdmVraXRfY29ubmVjdG9yX3R3",
            "aWxpby5wcm90bzLsAwoJQ29ubmVjdG9yElcKEERpYWxXaGF0c0FwcENhbGwS",
            "IC5saXZla2l0LkRpYWxXaGF0c0FwcENhbGxSZXF1ZXN0GiEubGl2ZWtpdC5E",
            "aWFsV2hhdHNBcHBDYWxsUmVzcG9uc2USaQoWRGlzY29ubmVjdFdoYXRzQXBw",
            "Q2FsbBImLmxpdmVraXQuRGlzY29ubmVjdFdoYXRzQXBwQ2FsbFJlcXVlc3Qa",
            "Jy5saXZla2l0LkRpc2Nvbm5lY3RXaGF0c0FwcENhbGxSZXNwb25zZRJgChND",
            "b25uZWN0V2hhdHNBcHBDYWxsEiMubGl2ZWtpdC5Db25uZWN0V2hhdHNBcHBD",
            "YWxsUmVxdWVzdBokLmxpdmVraXQuQ29ubmVjdFdoYXRzQXBwQ2FsbFJlc3Bv",
            "bnNlEl0KEkFjY2VwdFdoYXRzQXBwQ2FsbBIiLmxpdmVraXQuQWNjZXB0V2hh",
            "dHNBcHBDYWxsUmVxdWVzdBojLmxpdmVraXQuQWNjZXB0V2hhdHNBcHBDYWxs",
            "UmVzcG9uc2USWgoRQ29ubmVjdFR3aWxpb0NhbGwSIS5saXZla2l0LkNvbm5l",
            "Y3RUd2lsaW9DYWxsUmVxdWVzdBoiLmxpdmVraXQuQ29ubmVjdFR3aWxpb0Nh",
            "bGxSZXNwb25zZUJGWiNnaXRodWIuY29tL2xpdmVraXQvcHJvdG9jb2wvbGl2",
            "ZWtpdKoCDUxpdmVLaXQuUHJvdG/qAg5MaXZlS2l0OjpQcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::LiveKit.Proto.LivekitConnectorWhatsappReflection.Descriptor, global::LiveKit.Proto.LivekitConnectorTwilioReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
