// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: livekit_connector_twilio.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LiveKit.Proto {

  /// <summary>Holder for reflection information generated from livekit_connector_twilio.proto</summary>
  public static partial class LivekitConnectorTwilioReflection {

    #region Descriptor
    /// <summary>File descriptor for livekit_connector_twilio.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LivekitConnectorTwilioReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5saXZla2l0X2Nvbm5lY3Rvcl90d2lsaW8ucHJvdG8SB2xpdmVraXQaHGxp",
            "dmVraXRfYWdlbnRfZGlzcGF0Y2gucHJvdG8inAQKGENvbm5lY3RUd2lsaW9D",
            "YWxsUmVxdWVzdBJUChV0d2lsaW9fY2FsbF9kaXJlY3Rpb24YASABKA4yNS5s",
            "aXZla2l0LkNvbm5lY3RUd2lsaW9DYWxsUmVxdWVzdC5Ud2lsaW9DYWxsRGly",
            "ZWN0aW9uEhEKCXJvb21fbmFtZRgCIAEoCRIqCgZhZ2VudHMYAyADKAsyGi5s",
            "aXZla2l0LlJvb21BZ2VudERpc3BhdGNoEhwKFHBhcnRpY2lwYW50X2lkZW50",
            "aXR5GAQgASgJEhgKEHBhcnRpY2lwYW50X25hbWUYBSABKAkSHAoUcGFydGlj",
            "aXBhbnRfbWV0YWRhdGEYBiABKAkSXAoWcGFydGljaXBhbnRfYXR0cmlidXRl",
            "cxgHIAMoCzI8LmxpdmVraXQuQ29ubmVjdFR3aWxpb0NhbGxSZXF1ZXN0LlBh",
            "cnRpY2lwYW50QXR0cmlidXRlc0VudHJ5EhsKE2Rlc3RpbmF0aW9uX2NvdW50",
            "cnkYCCABKAkaPAoaUGFydGljaXBhbnRBdHRyaWJ1dGVzRW50cnkSCwoDa2V5",
            "GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASJcChNUd2lsaW9DYWxsRGlyZWN0",
            "aW9uEiEKHVRXSUxJT19DQUxMX0RJUkVDVElPTl9JTkJPVU5EEAASIgoeVFdJ",
            "TElPX0NBTExfRElSRUNUSU9OX09VVEJPVU5EEAEiMAoZQ29ubmVjdFR3aWxp",
            "b0NhbGxSZXNwb25zZRITCgtjb25uZWN0X3VybBgBIAEoCUJGWiNnaXRodWIu",
            "Y29tL2xpdmVraXQvcHJvdG9jb2wvbGl2ZWtpdKoCDUxpdmVLaXQuUHJvdG/q",
            "Ag5MaXZlS2l0OjpQcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::LiveKit.Proto.LivekitAgentDispatchReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveKit.Proto.ConnectTwilioCallRequest), global::LiveKit.Proto.ConnectTwilioCallRequest.Parser, new[]{ "TwilioCallDirection", "RoomName", "Agents", "ParticipantIdentity", "ParticipantName", "ParticipantMetadata", "ParticipantAttributes", "DestinationCountry" }, null, new[]{ typeof(global::LiveKit.Proto.ConnectTwilioCallRequest.Types.TwilioCallDirection) }, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveKit.Proto.ConnectTwilioCallResponse), global::LiveKit.Proto.ConnectTwilioCallResponse.Parser, new[]{ "ConnectUrl" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ConnectTwilioCallRequest : pb::IMessage<ConnectTwilioCallRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConnectTwilioCallRequest> _parser = new pb::MessageParser<ConnectTwilioCallRequest>(() => new ConnectTwilioCallRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ConnectTwilioCallRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LiveKit.Proto.LivekitConnectorTwilioReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConnectTwilioCallRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConnectTwilioCallRequest(ConnectTwilioCallRequest other) : this() {
      twilioCallDirection_ = other.twilioCallDirection_;
      roomName_ = other.roomName_;
      agents_ = other.agents_.Clone();
      participantIdentity_ = other.participantIdentity_;
      participantName_ = other.participantName_;
      participantMetadata_ = other.participantMetadata_;
      participantAttributes_ = other.participantAttributes_.Clone();
      destinationCountry_ = other.destinationCountry_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConnectTwilioCallRequest Clone() {
      return new ConnectTwilioCallRequest(this);
    }

    /// <summary>Field number for the "twilio_call_direction" field.</summary>
    public const int TwilioCallDirectionFieldNumber = 1;
    private global::LiveKit.Proto.ConnectTwilioCallRequest.Types.TwilioCallDirection twilioCallDirection_ = global::LiveKit.Proto.ConnectTwilioCallRequest.Types.TwilioCallDirection.Inbound;
    /// <summary>
    /// The Direction of the call
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LiveKit.Proto.ConnectTwilioCallRequest.Types.TwilioCallDirection TwilioCallDirection {
      get { return twilioCallDirection_; }
      set {
        twilioCallDirection_ = value;
      }
    }

    /// <summary>Field number for the "room_name" field.</summary>
    public const int RoomNameFieldNumber = 2;
    private string roomName_ = "";
    /// <summary>
    /// What LiveKit room should this call be connected to
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RoomName {
      get { return roomName_; }
      set {
        roomName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "agents" field.</summary>
    public const int AgentsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::LiveKit.Proto.RoomAgentDispatch> _repeated_agents_codec
        = pb::FieldCodec.ForMessage(26, global::LiveKit.Proto.RoomAgentDispatch.Parser);
    private readonly pbc::RepeatedField<global::LiveKit.Proto.RoomAgentDispatch> agents_ = new pbc::RepeatedField<global::LiveKit.Proto.RoomAgentDispatch>();
    /// <summary>
    /// Optional agents to dispatch the call to
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::LiveKit.Proto.RoomAgentDispatch> Agents {
      get { return agents_; }
    }

    /// <summary>Field number for the "participant_identity" field.</summary>
    public const int ParticipantIdentityFieldNumber = 4;
    private string participantIdentity_ = "";
    /// <summary>
    /// Optional identity of the participant in LiveKit room
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ParticipantIdentity {
      get { return participantIdentity_; }
      set {
        participantIdentity_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "participant_name" field.</summary>
    public const int ParticipantNameFieldNumber = 5;
    private string participantName_ = "";
    /// <summary>
    /// Optional name of the participant in LiveKit room
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ParticipantName {
      get { return participantName_; }
      set {
        participantName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "participant_metadata" field.</summary>
    public const int ParticipantMetadataFieldNumber = 6;
    private string participantMetadata_ = "";
    /// <summary>
    /// Optional user-defined metadata. Will be attached to a created Participant in the room.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ParticipantMetadata {
      get { return participantMetadata_; }
      set {
        participantMetadata_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "participant_attributes" field.</summary>
    public const int ParticipantAttributesFieldNumber = 7;
    private static readonly pbc::MapField<string, string>.Codec _map_participantAttributes_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 58);
    private readonly pbc::MapField<string, string> participantAttributes_ = new pbc::MapField<string, string>();
    /// <summary>
    /// Optional user-defined attributes. Will be attached to a created Participant in the room.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> ParticipantAttributes {
      get { return participantAttributes_; }
    }

    /// <summary>Field number for the "destination_country" field.</summary>
    public const int DestinationCountryFieldNumber = 8;
    private string destinationCountry_ = "";
    /// <summary>
    /// Country where the call terminates as ISO 3166-1 alpha-2 (https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). This will be used by the livekit infrastructure to route calls.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DestinationCountry {
      get { return destinationCountry_; }
      set {
        destinationCountry_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ConnectTwilioCallRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ConnectTwilioCallRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TwilioCallDirection != other.TwilioCallDirection) return false;
      if (RoomName != other.RoomName) return false;
      if(!agents_.Equals(other.agents_)) return false;
      if (ParticipantIdentity != other.ParticipantIdentity) return false;
      if (ParticipantName != other.ParticipantName) return false;
      if (ParticipantMetadata != other.ParticipantMetadata) return false;
      if (!ParticipantAttributes.Equals(other.ParticipantAttributes)) return false;
      if (DestinationCountry != other.DestinationCountry) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TwilioCallDirection != global::LiveKit.Proto.ConnectTwilioCallRequest.Types.TwilioCallDirection.Inbound) hash ^= TwilioCallDirection.GetHashCode();
      if (RoomName.Length != 0) hash ^= RoomName.GetHashCode();
      hash ^= agents_.GetHashCode();
      if (ParticipantIdentity.Length != 0) hash ^= ParticipantIdentity.GetHashCode();
      if (ParticipantName.Length != 0) hash ^= ParticipantName.GetHashCode();
      if (ParticipantMetadata.Length != 0) hash ^= ParticipantMetadata.GetHashCode();
      hash ^= ParticipantAttributes.GetHashCode();
      if (DestinationCountry.Length != 0) hash ^= DestinationCountry.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TwilioCallDirection != global::LiveKit.Proto.ConnectTwilioCallRequest.Types.TwilioCallDirection.Inbound) {
        output.WriteRawTag(8);
        output.WriteEnum((int) TwilioCallDirection);
      }
      if (RoomName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RoomName);
      }
      agents_.WriteTo(output, _repeated_agents_codec);
      if (ParticipantIdentity.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ParticipantIdentity);
      }
      if (ParticipantName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ParticipantName);
      }
      if (ParticipantMetadata.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ParticipantMetadata);
      }
      participantAttributes_.WriteTo(output, _map_participantAttributes_codec);
      if (DestinationCountry.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(DestinationCountry);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TwilioCallDirection != global::LiveKit.Proto.ConnectTwilioCallRequest.Types.TwilioCallDirection.Inbound) {
        output.WriteRawTag(8);
        output.WriteEnum((int) TwilioCallDirection);
      }
      if (RoomName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RoomName);
      }
      agents_.WriteTo(ref output, _repeated_agents_codec);
      if (ParticipantIdentity.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ParticipantIdentity);
      }
      if (ParticipantName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ParticipantName);
      }
      if (ParticipantMetadata.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ParticipantMetadata);
      }
      participantAttributes_.WriteTo(ref output, _map_participantAttributes_codec);
      if (DestinationCountry.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(DestinationCountry);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TwilioCallDirection != global::LiveKit.Proto.ConnectTwilioCallRequest.Types.TwilioCallDirection.Inbound) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TwilioCallDirection);
      }
      if (RoomName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomName);
      }
      size += agents_.CalculateSize(_repeated_agents_codec);
      if (ParticipantIdentity.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParticipantIdentity);
      }
      if (ParticipantName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParticipantName);
      }
      if (ParticipantMetadata.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParticipantMetadata);
      }
      size += participantAttributes_.CalculateSize(_map_participantAttributes_codec);
      if (DestinationCountry.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DestinationCountry);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ConnectTwilioCallRequest other) {
      if (other == null) {
        return;
      }
      if (other.TwilioCallDirection != global::LiveKit.Proto.ConnectTwilioCallRequest.Types.TwilioCallDirection.Inbound) {
        TwilioCallDirection = other.TwilioCallDirection;
      }
      if (other.RoomName.Length != 0) {
        RoomName = other.RoomName;
      }
      agents_.Add(other.agents_);
      if (other.ParticipantIdentity.Length != 0) {
        ParticipantIdentity = other.ParticipantIdentity;
      }
      if (other.ParticipantName.Length != 0) {
        ParticipantName = other.ParticipantName;
      }
      if (other.ParticipantMetadata.Length != 0) {
        ParticipantMetadata = other.ParticipantMetadata;
      }
      participantAttributes_.MergeFrom(other.participantAttributes_);
      if (other.DestinationCountry.Length != 0) {
        DestinationCountry = other.DestinationCountry;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TwilioCallDirection = (global::LiveKit.Proto.ConnectTwilioCallRequest.Types.TwilioCallDirection) input.ReadEnum();
            break;
          }
          case 18: {
            RoomName = input.ReadString();
            break;
          }
          case 26: {
            agents_.AddEntriesFrom(input, _repeated_agents_codec);
            break;
          }
          case 34: {
            ParticipantIdentity = input.ReadString();
            break;
          }
          case 42: {
            ParticipantName = input.ReadString();
            break;
          }
          case 50: {
            ParticipantMetadata = input.ReadString();
            break;
          }
          case 58: {
            participantAttributes_.AddEntriesFrom(input, _map_participantAttributes_codec);
            break;
          }
          case 66: {
            DestinationCountry = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TwilioCallDirection = (global::LiveKit.Proto.ConnectTwilioCallRequest.Types.TwilioCallDirection) input.ReadEnum();
            break;
          }
          case 18: {
            RoomName = input.ReadString();
            break;
          }
          case 26: {
            agents_.AddEntriesFrom(ref input, _repeated_agents_codec);
            break;
          }
          case 34: {
            ParticipantIdentity = input.ReadString();
            break;
          }
          case 42: {
            ParticipantName = input.ReadString();
            break;
          }
          case 50: {
            ParticipantMetadata = input.ReadString();
            break;
          }
          case 58: {
            participantAttributes_.AddEntriesFrom(ref input, _map_participantAttributes_codec);
            break;
          }
          case 66: {
            DestinationCountry = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ConnectTwilioCallRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum TwilioCallDirection {
        /// <summary>
        /// Call is inbound to LiveKit from Twilio
        /// </summary>
        [pbr::OriginalName("TWILIO_CALL_DIRECTION_INBOUND")] Inbound = 0,
        /// <summary>
        /// Call is outbound from LiveKit to Twilio
        /// </summary>
        [pbr::OriginalName("TWILIO_CALL_DIRECTION_OUTBOUND")] Outbound = 1,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ConnectTwilioCallResponse : pb::IMessage<ConnectTwilioCallResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConnectTwilioCallResponse> _parser = new pb::MessageParser<ConnectTwilioCallResponse>(() => new ConnectTwilioCallResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ConnectTwilioCallResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LiveKit.Proto.LivekitConnectorTwilioReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConnectTwilioCallResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConnectTwilioCallResponse(ConnectTwilioCallResponse other) : this() {
      connectUrl_ = other.connectUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConnectTwilioCallResponse Clone() {
      return new ConnectTwilioCallResponse(this);
    }

    /// <summary>Field number for the "connect_url" field.</summary>
    public const int ConnectUrlFieldNumber = 1;
    private string connectUrl_ = "";
    /// <summary>
    /// The websocket URL which twilio media stream will connect to
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ConnectUrl {
      get { return connectUrl_; }
      set {
        connectUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ConnectTwilioCallResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ConnectTwilioCallResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ConnectUrl != other.ConnectUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ConnectUrl.Length != 0) hash ^= ConnectUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ConnectUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ConnectUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ConnectUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ConnectUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ConnectUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ConnectUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ConnectTwilioCallResponse other) {
      if (other == null) {
        return;
      }
      if (other.ConnectUrl.Length != 0) {
        ConnectUrl = other.ConnectUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ConnectUrl = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ConnectUrl = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
