// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: logger/options.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Logger {

  /// <summary>Holder for reflection information generated from logger/options.proto</summary>
  public static partial class OptionsReflection {

    #region Descriptor
    /// <summary>File descriptor for logger/options.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OptionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRsb2dnZXIvb3B0aW9ucy5wcm90bxIGbG9nZ2VyGiBnb29nbGUvcHJvdG9i",
            "dWYvZGVzY3JpcHRvci5wcm90bzovCgZyZWRhY3QSHS5nb29nbGUucHJvdG9i",
            "dWYuRmllbGRPcHRpb25zGNGGAyABKAhCJFoiZ2l0aHViLmNvbS9saXZla2l0",
            "L3Byb3RvY29sL2xvZ2dlcmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { OptionsExtensions.Redact }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of logger/options.proto</summary>
  public static partial class OptionsExtensions {
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> Redact =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(50001, pb::FieldCodec.ForBool(400008, false));
  }

}

#endregion Designer generated code
