// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: agent/livekit_agent_dev.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Livekit.Agent {

  /// <summary>Holder for reflection information generated from agent/livekit_agent_dev.proto</summary>
  public static partial class LivekitAgentDevReflection {

    #region Descriptor
    /// <summary>File descriptor for agent/livekit_agent_dev.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LivekitAgentDevReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1hZ2VudC9saXZla2l0X2FnZW50X2Rldi5wcm90bxINbGl2ZWtpdC5hZ2Vu",
            "dCLuAQoPQWdlbnREZXZNZXNzYWdlEk0KGGdldF9ydW5uaW5nX2pvYnNfcmVx",
            "dWVzdBgBIAEoCzIpLmxpdmVraXQuYWdlbnQuR2V0UnVubmluZ0FnZW50Sm9i",
            "c1JlcXVlc3RIABJPChlnZXRfcnVubmluZ19qb2JzX3Jlc3BvbnNlGAIgASgL",
            "MioubGl2ZWtpdC5hZ2VudC5HZXRSdW5uaW5nQWdlbnRKb2JzUmVzcG9uc2VI",
            "ABIwCgtzZXJ2ZXJfaW5mbxgDIAEoCzIZLmxpdmVraXQuYWdlbnQuU2VydmVy",
            "SW5mb0gAQgkKB21lc3NhZ2UiLQoKU2VydmVySW5mbxISCgphZ2VudF9uYW1l",
            "GAEgASgJEgsKA3VybBgCIAEoCSIcChpHZXRSdW5uaW5nQWdlbnRKb2JzUmVx",
            "dWVzdCJPChtHZXRSdW5uaW5nQWdlbnRKb2JzUmVzcG9uc2USMAoEam9icxgB",
            "IAMoCzIiLmxpdmVraXQuYWdlbnQuUnVubmluZ0FnZW50Sm9iSW5mbyKqAQoT",
            "UnVubmluZ0FnZW50Sm9iSW5mbxILCgNqb2IYASABKAwSEwoLYWNjZXB0X25h",
            "bWUYAiABKAkSFwoPYWNjZXB0X2lkZW50aXR5GAMgASgJEhcKD2FjY2VwdF9t",
            "ZXRhZGF0YRgEIAEoCRILCgN1cmwYBSABKAkSDQoFdG9rZW4YBiABKAkSEQoJ",
            "d29ya2VyX2lkGAcgASgJEhAKCG1vY2tfam9iGAggASgIQitaKWdpdGh1Yi5j",
            "b20vbGl2ZWtpdC9wcm90b2NvbC9saXZla2l0L2FnZW50YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Livekit.Agent.AgentDevMessage), global::Livekit.Agent.AgentDevMessage.Parser, new[]{ "GetRunningJobsRequest", "GetRunningJobsResponse", "ServerInfo" }, new[]{ "Message" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Livekit.Agent.ServerInfo), global::Livekit.Agent.ServerInfo.Parser, new[]{ "AgentName", "Url" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Livekit.Agent.GetRunningAgentJobsRequest), global::Livekit.Agent.GetRunningAgentJobsRequest.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Livekit.Agent.GetRunningAgentJobsResponse), global::Livekit.Agent.GetRunningAgentJobsResponse.Parser, new[]{ "Jobs" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Livekit.Agent.RunningAgentJobInfo), global::Livekit.Agent.RunningAgentJobInfo.Parser, new[]{ "Job", "AcceptName", "AcceptIdentity", "AcceptMetadata", "Url", "Token", "WorkerId", "MockJob" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// AgentDevMessage is used for IPC between the CLI and agent processes
  /// during dev-mode hot reload.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AgentDevMessage : pb::IMessage<AgentDevMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AgentDevMessage> _parser = new pb::MessageParser<AgentDevMessage>(() => new AgentDevMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AgentDevMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Livekit.Agent.LivekitAgentDevReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentDevMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentDevMessage(AgentDevMessage other) : this() {
      switch (other.MessageCase) {
        case MessageOneofCase.GetRunningJobsRequest:
          GetRunningJobsRequest = other.GetRunningJobsRequest.Clone();
          break;
        case MessageOneofCase.GetRunningJobsResponse:
          GetRunningJobsResponse = other.GetRunningJobsResponse.Clone();
          break;
        case MessageOneofCase.ServerInfo:
          ServerInfo = other.ServerInfo.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentDevMessage Clone() {
      return new AgentDevMessage(this);
    }

    /// <summary>Field number for the "get_running_jobs_request" field.</summary>
    public const int GetRunningJobsRequestFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Livekit.Agent.GetRunningAgentJobsRequest GetRunningJobsRequest {
      get { return messageCase_ == MessageOneofCase.GetRunningJobsRequest ? (global::Livekit.Agent.GetRunningAgentJobsRequest) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.GetRunningJobsRequest;
      }
    }

    /// <summary>Field number for the "get_running_jobs_response" field.</summary>
    public const int GetRunningJobsResponseFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Livekit.Agent.GetRunningAgentJobsResponse GetRunningJobsResponse {
      get { return messageCase_ == MessageOneofCase.GetRunningJobsResponse ? (global::Livekit.Agent.GetRunningAgentJobsResponse) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.GetRunningJobsResponse;
      }
    }

    /// <summary>Field number for the "server_info" field.</summary>
    public const int ServerInfoFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Livekit.Agent.ServerInfo ServerInfo {
      get { return messageCase_ == MessageOneofCase.ServerInfo ? (global::Livekit.Agent.ServerInfo) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.ServerInfo;
      }
    }

    private object message_;
    /// <summary>Enum of possible cases for the "message" oneof.</summary>
    public enum MessageOneofCase {
      None = 0,
      GetRunningJobsRequest = 1,
      GetRunningJobsResponse = 2,
      ServerInfo = 3,
    }
    private MessageOneofCase messageCase_ = MessageOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageOneofCase MessageCase {
      get { return messageCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMessage() {
      messageCase_ = MessageOneofCase.None;
      message_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AgentDevMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AgentDevMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(GetRunningJobsRequest, other.GetRunningJobsRequest)) return false;
      if (!object.Equals(GetRunningJobsResponse, other.GetRunningJobsResponse)) return false;
      if (!object.Equals(ServerInfo, other.ServerInfo)) return false;
      if (MessageCase != other.MessageCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (messageCase_ == MessageOneofCase.GetRunningJobsRequest) hash ^= GetRunningJobsRequest.GetHashCode();
      if (messageCase_ == MessageOneofCase.GetRunningJobsResponse) hash ^= GetRunningJobsResponse.GetHashCode();
      if (messageCase_ == MessageOneofCase.ServerInfo) hash ^= ServerInfo.GetHashCode();
      hash ^= (int) messageCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (messageCase_ == MessageOneofCase.GetRunningJobsRequest) {
        output.WriteRawTag(10);
        output.WriteMessage(GetRunningJobsRequest);
      }
      if (messageCase_ == MessageOneofCase.GetRunningJobsResponse) {
        output.WriteRawTag(18);
        output.WriteMessage(GetRunningJobsResponse);
      }
      if (messageCase_ == MessageOneofCase.ServerInfo) {
        output.WriteRawTag(26);
        output.WriteMessage(ServerInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (messageCase_ == MessageOneofCase.GetRunningJobsRequest) {
        output.WriteRawTag(10);
        output.WriteMessage(GetRunningJobsRequest);
      }
      if (messageCase_ == MessageOneofCase.GetRunningJobsResponse) {
        output.WriteRawTag(18);
        output.WriteMessage(GetRunningJobsResponse);
      }
      if (messageCase_ == MessageOneofCase.ServerInfo) {
        output.WriteRawTag(26);
        output.WriteMessage(ServerInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (messageCase_ == MessageOneofCase.GetRunningJobsRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GetRunningJobsRequest);
      }
      if (messageCase_ == MessageOneofCase.GetRunningJobsResponse) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GetRunningJobsResponse);
      }
      if (messageCase_ == MessageOneofCase.ServerInfo) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ServerInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AgentDevMessage other) {
      if (other == null) {
        return;
      }
      switch (other.MessageCase) {
        case MessageOneofCase.GetRunningJobsRequest:
          if (GetRunningJobsRequest == null) {
            GetRunningJobsRequest = new global::Livekit.Agent.GetRunningAgentJobsRequest();
          }
          GetRunningJobsRequest.MergeFrom(other.GetRunningJobsRequest);
          break;
        case MessageOneofCase.GetRunningJobsResponse:
          if (GetRunningJobsResponse == null) {
            GetRunningJobsResponse = new global::Livekit.Agent.GetRunningAgentJobsResponse();
          }
          GetRunningJobsResponse.MergeFrom(other.GetRunningJobsResponse);
          break;
        case MessageOneofCase.ServerInfo:
          if (ServerInfo == null) {
            ServerInfo = new global::Livekit.Agent.ServerInfo();
          }
          ServerInfo.MergeFrom(other.ServerInfo);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Livekit.Agent.GetRunningAgentJobsRequest subBuilder = new global::Livekit.Agent.GetRunningAgentJobsRequest();
            if (messageCase_ == MessageOneofCase.GetRunningJobsRequest) {
              subBuilder.MergeFrom(GetRunningJobsRequest);
            }
            input.ReadMessage(subBuilder);
            GetRunningJobsRequest = subBuilder;
            break;
          }
          case 18: {
            global::Livekit.Agent.GetRunningAgentJobsResponse subBuilder = new global::Livekit.Agent.GetRunningAgentJobsResponse();
            if (messageCase_ == MessageOneofCase.GetRunningJobsResponse) {
              subBuilder.MergeFrom(GetRunningJobsResponse);
            }
            input.ReadMessage(subBuilder);
            GetRunningJobsResponse = subBuilder;
            break;
          }
          case 26: {
            global::Livekit.Agent.ServerInfo subBuilder = new global::Livekit.Agent.ServerInfo();
            if (messageCase_ == MessageOneofCase.ServerInfo) {
              subBuilder.MergeFrom(ServerInfo);
            }
            input.ReadMessage(subBuilder);
            ServerInfo = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Livekit.Agent.GetRunningAgentJobsRequest subBuilder = new global::Livekit.Agent.GetRunningAgentJobsRequest();
            if (messageCase_ == MessageOneofCase.GetRunningJobsRequest) {
              subBuilder.MergeFrom(GetRunningJobsRequest);
            }
            input.ReadMessage(subBuilder);
            GetRunningJobsRequest = subBuilder;
            break;
          }
          case 18: {
            global::Livekit.Agent.GetRunningAgentJobsResponse subBuilder = new global::Livekit.Agent.GetRunningAgentJobsResponse();
            if (messageCase_ == MessageOneofCase.GetRunningJobsResponse) {
              subBuilder.MergeFrom(GetRunningJobsResponse);
            }
            input.ReadMessage(subBuilder);
            GetRunningJobsResponse = subBuilder;
            break;
          }
          case 26: {
            global::Livekit.Agent.ServerInfo subBuilder = new global::Livekit.Agent.ServerInfo();
            if (messageCase_ == MessageOneofCase.ServerInfo) {
              subBuilder.MergeFrom(ServerInfo);
            }
            input.ReadMessage(subBuilder);
            ServerInfo = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ServerInfo is sent by the agent to the CLI when the dev-reload channel opens,
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ServerInfo : pb::IMessage<ServerInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ServerInfo> _parser = new pb::MessageParser<ServerInfo>(() => new ServerInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ServerInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Livekit.Agent.LivekitAgentDevReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerInfo(ServerInfo other) : this() {
      agentName_ = other.agentName_;
      url_ = other.url_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerInfo Clone() {
      return new ServerInfo(this);
    }

    /// <summary>Field number for the "agent_name" field.</summary>
    public const int AgentNameFieldNumber = 1;
    private string agentName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AgentName {
      get { return agentName_; }
      set {
        agentName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 2;
    private string url_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Url {
      get { return url_; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ServerInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ServerInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AgentName != other.AgentName) return false;
      if (Url != other.Url) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AgentName.Length != 0) hash ^= AgentName.GetHashCode();
      if (Url.Length != 0) hash ^= Url.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AgentName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AgentName);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Url);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AgentName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AgentName);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Url);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AgentName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AgentName);
      }
      if (Url.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ServerInfo other) {
      if (other == null) {
        return;
      }
      if (other.AgentName.Length != 0) {
        AgentName = other.AgentName;
      }
      if (other.Url.Length != 0) {
        Url = other.Url;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AgentName = input.ReadString();
            break;
          }
          case 18: {
            Url = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AgentName = input.ReadString();
            break;
          }
          case 18: {
            Url = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetRunningAgentJobsRequest : pb::IMessage<GetRunningAgentJobsRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetRunningAgentJobsRequest> _parser = new pb::MessageParser<GetRunningAgentJobsRequest>(() => new GetRunningAgentJobsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetRunningAgentJobsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Livekit.Agent.LivekitAgentDevReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRunningAgentJobsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRunningAgentJobsRequest(GetRunningAgentJobsRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRunningAgentJobsRequest Clone() {
      return new GetRunningAgentJobsRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetRunningAgentJobsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetRunningAgentJobsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetRunningAgentJobsRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetRunningAgentJobsResponse : pb::IMessage<GetRunningAgentJobsResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetRunningAgentJobsResponse> _parser = new pb::MessageParser<GetRunningAgentJobsResponse>(() => new GetRunningAgentJobsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetRunningAgentJobsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Livekit.Agent.LivekitAgentDevReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRunningAgentJobsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRunningAgentJobsResponse(GetRunningAgentJobsResponse other) : this() {
      jobs_ = other.jobs_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRunningAgentJobsResponse Clone() {
      return new GetRunningAgentJobsResponse(this);
    }

    /// <summary>Field number for the "jobs" field.</summary>
    public const int JobsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Livekit.Agent.RunningAgentJobInfo> _repeated_jobs_codec
        = pb::FieldCodec.ForMessage(10, global::Livekit.Agent.RunningAgentJobInfo.Parser);
    private readonly pbc::RepeatedField<global::Livekit.Agent.RunningAgentJobInfo> jobs_ = new pbc::RepeatedField<global::Livekit.Agent.RunningAgentJobInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Livekit.Agent.RunningAgentJobInfo> Jobs {
      get { return jobs_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetRunningAgentJobsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetRunningAgentJobsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!jobs_.Equals(other.jobs_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= jobs_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      jobs_.WriteTo(output, _repeated_jobs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      jobs_.WriteTo(ref output, _repeated_jobs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += jobs_.CalculateSize(_repeated_jobs_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetRunningAgentJobsResponse other) {
      if (other == null) {
        return;
      }
      jobs_.Add(other.jobs_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            jobs_.AddEntriesFrom(input, _repeated_jobs_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            jobs_.AddEntriesFrom(ref input, _repeated_jobs_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RunningAgentJobInfo : pb::IMessage<RunningAgentJobInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RunningAgentJobInfo> _parser = new pb::MessageParser<RunningAgentJobInfo>(() => new RunningAgentJobInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RunningAgentJobInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Livekit.Agent.LivekitAgentDevReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RunningAgentJobInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RunningAgentJobInfo(RunningAgentJobInfo other) : this() {
      job_ = other.job_;
      acceptName_ = other.acceptName_;
      acceptIdentity_ = other.acceptIdentity_;
      acceptMetadata_ = other.acceptMetadata_;
      url_ = other.url_;
      token_ = other.token_;
      workerId_ = other.workerId_;
      mockJob_ = other.mockJob_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RunningAgentJobInfo Clone() {
      return new RunningAgentJobInfo(this);
    }

    /// <summary>Field number for the "job" field.</summary>
    public const int JobFieldNumber = 1;
    private pb::ByteString job_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Job {
      get { return job_; }
      set {
        job_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "accept_name" field.</summary>
    public const int AcceptNameFieldNumber = 2;
    private string acceptName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AcceptName {
      get { return acceptName_; }
      set {
        acceptName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "accept_identity" field.</summary>
    public const int AcceptIdentityFieldNumber = 3;
    private string acceptIdentity_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AcceptIdentity {
      get { return acceptIdentity_; }
      set {
        acceptIdentity_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "accept_metadata" field.</summary>
    public const int AcceptMetadataFieldNumber = 4;
    private string acceptMetadata_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AcceptMetadata {
      get { return acceptMetadata_; }
      set {
        acceptMetadata_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 5;
    private string url_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Url {
      get { return url_; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 6;
    private string token_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "worker_id" field.</summary>
    public const int WorkerIdFieldNumber = 7;
    private string workerId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WorkerId {
      get { return workerId_; }
      set {
        workerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mock_job" field.</summary>
    public const int MockJobFieldNumber = 8;
    private bool mockJob_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool MockJob {
      get { return mockJob_; }
      set {
        mockJob_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RunningAgentJobInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RunningAgentJobInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Job != other.Job) return false;
      if (AcceptName != other.AcceptName) return false;
      if (AcceptIdentity != other.AcceptIdentity) return false;
      if (AcceptMetadata != other.AcceptMetadata) return false;
      if (Url != other.Url) return false;
      if (Token != other.Token) return false;
      if (WorkerId != other.WorkerId) return false;
      if (MockJob != other.MockJob) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Job.Length != 0) hash ^= Job.GetHashCode();
      if (AcceptName.Length != 0) hash ^= AcceptName.GetHashCode();
      if (AcceptIdentity.Length != 0) hash ^= AcceptIdentity.GetHashCode();
      if (AcceptMetadata.Length != 0) hash ^= AcceptMetadata.GetHashCode();
      if (Url.Length != 0) hash ^= Url.GetHashCode();
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (WorkerId.Length != 0) hash ^= WorkerId.GetHashCode();
      if (MockJob != false) hash ^= MockJob.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Job.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Job);
      }
      if (AcceptName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AcceptName);
      }
      if (AcceptIdentity.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AcceptIdentity);
      }
      if (AcceptMetadata.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AcceptMetadata);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Url);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Token);
      }
      if (WorkerId.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(WorkerId);
      }
      if (MockJob != false) {
        output.WriteRawTag(64);
        output.WriteBool(MockJob);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Job.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Job);
      }
      if (AcceptName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AcceptName);
      }
      if (AcceptIdentity.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AcceptIdentity);
      }
      if (AcceptMetadata.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AcceptMetadata);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Url);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Token);
      }
      if (WorkerId.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(WorkerId);
      }
      if (MockJob != false) {
        output.WriteRawTag(64);
        output.WriteBool(MockJob);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Job.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Job);
      }
      if (AcceptName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AcceptName);
      }
      if (AcceptIdentity.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AcceptIdentity);
      }
      if (AcceptMetadata.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AcceptMetadata);
      }
      if (Url.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (WorkerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WorkerId);
      }
      if (MockJob != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RunningAgentJobInfo other) {
      if (other == null) {
        return;
      }
      if (other.Job.Length != 0) {
        Job = other.Job;
      }
      if (other.AcceptName.Length != 0) {
        AcceptName = other.AcceptName;
      }
      if (other.AcceptIdentity.Length != 0) {
        AcceptIdentity = other.AcceptIdentity;
      }
      if (other.AcceptMetadata.Length != 0) {
        AcceptMetadata = other.AcceptMetadata;
      }
      if (other.Url.Length != 0) {
        Url = other.Url;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      if (other.WorkerId.Length != 0) {
        WorkerId = other.WorkerId;
      }
      if (other.MockJob != false) {
        MockJob = other.MockJob;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Job = input.ReadBytes();
            break;
          }
          case 18: {
            AcceptName = input.ReadString();
            break;
          }
          case 26: {
            AcceptIdentity = input.ReadString();
            break;
          }
          case 34: {
            AcceptMetadata = input.ReadString();
            break;
          }
          case 42: {
            Url = input.ReadString();
            break;
          }
          case 50: {
            Token = input.ReadString();
            break;
          }
          case 58: {
            WorkerId = input.ReadString();
            break;
          }
          case 64: {
            MockJob = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Job = input.ReadBytes();
            break;
          }
          case 18: {
            AcceptName = input.ReadString();
            break;
          }
          case 26: {
            AcceptIdentity = input.ReadString();
            break;
          }
          case 34: {
            AcceptMetadata = input.ReadString();
            break;
          }
          case 42: {
            Url = input.ReadString();
            break;
          }
          case 50: {
            Token = input.ReadString();
            break;
          }
          case 58: {
            WorkerId = input.ReadString();
            break;
          }
          case 64: {
            MockJob = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
