// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: agent/livekit_agent_text.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LiveKit.Proto {

  /// <summary>Holder for reflection information generated from agent/livekit_agent_text.proto</summary>
  public static partial class LivekitAgentTextReflection {

    #region Descriptor
    /// <summary>File descriptor for agent/livekit_agent_text.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LivekitAgentTextReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5hZ2VudC9saXZla2l0X2FnZW50X3RleHQucHJvdG8SDWxpdmVraXQuYWdl",
            "bnQaIWFnZW50L2xpdmVraXRfYWdlbnRfc2Vzc2lvbi5wcm90bxoUbG9nZ2Vy",
            "L29wdGlvbnMucHJvdG8i3gEKElRleHRNZXNzYWdlUmVxdWVzdBIMCgR0ZXh0",
            "GAEgASgJEiEKCm1lc3NhZ2VfaWQYAiABKAlCDZrsLAltZXNzYWdlSUQSIQoK",
            "c2Vzc2lvbl9pZBgDIAEoCUINmuwsCXNlc3Npb25JRBISCgphZ2VudF9uYW1l",
            "GAQgASgJEhAKCG1ldGFkYXRhGAUgASgJEjwKDXNlc3Npb25fc3RhdGUYBiAB",
            "KAsyIC5saXZla2l0LmFnZW50LkFnZW50U2Vzc2lvblN0YXRlSACIAQFCEAoO",
            "X3Nlc3Npb25fc3RhdGUi+gIKE1RleHRNZXNzYWdlUmVzcG9uc2USIQoKbWVz",
            "c2FnZV9pZBgBIAEoCUINmuwsCW1lc3NhZ2VJRBIhCgpzZXNzaW9uX2lkGAIg",
            "ASgJQg2a7CwJc2Vzc2lvbklEEi0KB21lc3NhZ2UYAyABKAsyGi5saXZla2l0",
            "LmFnZW50LkNoYXRNZXNzYWdlSAASNAoNZnVuY3Rpb25fY2FsbBgEIAEoCzIb",
            "LmxpdmVraXQuYWdlbnQuRnVuY3Rpb25DYWxsSAASQQoUZnVuY3Rpb25fY2Fs",
            "bF9vdXRwdXQYBSABKAsyIS5saXZla2l0LmFnZW50LkZ1bmN0aW9uQ2FsbE91",
            "dHB1dEgAEjQKDWFnZW50X2hhbmRvZmYYBiABKAsyGy5saXZla2l0LmFnZW50",
            "LkFnZW50SGFuZG9mZkgAEjYKCGNvbXBsZXRlGAcgASgLMiIubGl2ZWtpdC5h",
            "Z2VudC5UZXh0TWVzc2FnZUNvbXBsZXRlSABCBwoFZXZlbnQijAEKE1RleHRN",
            "ZXNzYWdlQ29tcGxldGUSOQoNc2Vzc2lvbl9zdGF0ZRgBIAEoCzIgLmxpdmVr",
            "aXQuYWdlbnQuQWdlbnRTZXNzaW9uU3RhdGVIABIwCgVlcnJvchgCIAEoCzIf",
            "LmxpdmVraXQuYWdlbnQuVGV4dE1lc3NhZ2VFcnJvckgAQggKBnJlc3VsdCJR",
            "ChFBZ2VudFNlc3Npb25TdGF0ZRIPCgd2ZXJzaW9uGAEgASgEEhIKCHNuYXBz",
            "aG90GAIgASgMSAASDwoFZGVsdGEYAyABKAxIAEIGCgRkYXRhIlYKEFRleHRN",
            "ZXNzYWdlRXJyb3ISDwoHbWVzc2FnZRgBIAEoCRIxCgRjb2RlGAIgASgOMiMu",
            "bGl2ZWtpdC5hZ2VudC5UZXh0TWVzc2FnZUVycm9yQ29kZSpzChRUZXh0TWVz",
            "c2FnZUVycm9yQ29kZRISCg5JTlRFUk5BTF9FUlJPUhAAEhsKF1NFU1NJT05f",
            "U1RBVEVfTk9UX0ZPVU5EEAESFgoSVEVYVF9IQU5ETEVSX0VSUk9SEAISEgoO",
            "UFJPQ0VTU19DTE9TRUQQA0JMWilnaXRodWIuY29tL2xpdmVraXQvcHJvdG9j",
            "b2wvbGl2ZWtpdC9hZ2VudKoCDUxpdmVLaXQuUHJvdG/qAg5MaXZlS2l0OjpQ",
            "cm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Livekit.Agent.LivekitAgentSessionReflection.Descriptor, global::LiveKit.Proto.OptionsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LiveKit.Proto.TextMessageErrorCode), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveKit.Proto.TextMessageRequest), global::LiveKit.Proto.TextMessageRequest.Parser, new[]{ "Text", "MessageId", "SessionId", "AgentName", "Metadata", "SessionState" }, new[]{ "SessionState" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveKit.Proto.TextMessageResponse), global::LiveKit.Proto.TextMessageResponse.Parser, new[]{ "MessageId", "SessionId", "Message", "FunctionCall", "FunctionCallOutput", "AgentHandoff", "Complete" }, new[]{ "Event" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveKit.Proto.TextMessageComplete), global::LiveKit.Proto.TextMessageComplete.Parser, new[]{ "SessionState", "Error" }, new[]{ "Result" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveKit.Proto.AgentSessionState), global::LiveKit.Proto.AgentSessionState.Parser, new[]{ "Version", "Snapshot", "Delta" }, new[]{ "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveKit.Proto.TextMessageError), global::LiveKit.Proto.TextMessageError.Parser, new[]{ "Message", "Code" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TextMessageErrorCode {
    /// <summary>
    /// Unexpected internal error
    /// </summary>
    [pbr::OriginalName("INTERNAL_ERROR")] InternalError = 0,
    /// <summary>
    /// Session state not found in cache or version mismatch
    /// </summary>
    [pbr::OriginalName("SESSION_STATE_NOT_FOUND")] SessionStateNotFound = 1,
    /// <summary>
    /// An exception was raised inside the user's text handler
    /// </summary>
    [pbr::OriginalName("TEXT_HANDLER_ERROR")] TextHandlerError = 2,
    /// <summary>
    /// The worker process exited before the text session completed
    /// </summary>
    [pbr::OriginalName("PROCESS_CLOSED")] ProcessClosed = 3,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Request to send a text message to an agent.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TextMessageRequest : pb::IMessage<TextMessageRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TextMessageRequest> _parser = new pb::MessageParser<TextMessageRequest>(() => new TextMessageRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TextMessageRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LiveKit.Proto.LivekitAgentTextReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextMessageRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextMessageRequest(TextMessageRequest other) : this() {
      text_ = other.text_;
      messageId_ = other.messageId_;
      sessionId_ = other.sessionId_;
      agentName_ = other.agentName_;
      metadata_ = other.metadata_;
      sessionState_ = other.sessionState_ != null ? other.sessionState_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextMessageRequest Clone() {
      return new TextMessageRequest(this);
    }

    /// <summary>Field number for the "text" field.</summary>
    public const int TextFieldNumber = 1;
    private string text_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Text {
      get { return text_; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "message_id" field.</summary>
    public const int MessageIdFieldNumber = 2;
    private string messageId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MessageId {
      get { return messageId_; }
      set {
        messageId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "session_id" field.</summary>
    public const int SessionIdFieldNumber = 3;
    private string sessionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SessionId {
      get { return sessionId_; }
      set {
        sessionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "agent_name" field.</summary>
    public const int AgentNameFieldNumber = 4;
    private string agentName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AgentName {
      get { return agentName_; }
      set {
        agentName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 5;
    private string metadata_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Metadata {
      get { return metadata_; }
      set {
        metadata_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "session_state" field.</summary>
    public const int SessionStateFieldNumber = 6;
    private global::LiveKit.Proto.AgentSessionState sessionState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LiveKit.Proto.AgentSessionState SessionState {
      get { return sessionState_; }
      set {
        sessionState_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TextMessageRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TextMessageRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Text != other.Text) return false;
      if (MessageId != other.MessageId) return false;
      if (SessionId != other.SessionId) return false;
      if (AgentName != other.AgentName) return false;
      if (Metadata != other.Metadata) return false;
      if (!object.Equals(SessionState, other.SessionState)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Text.Length != 0) hash ^= Text.GetHashCode();
      if (MessageId.Length != 0) hash ^= MessageId.GetHashCode();
      if (SessionId.Length != 0) hash ^= SessionId.GetHashCode();
      if (AgentName.Length != 0) hash ^= AgentName.GetHashCode();
      if (Metadata.Length != 0) hash ^= Metadata.GetHashCode();
      if (sessionState_ != null) hash ^= SessionState.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Text.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      if (MessageId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MessageId);
      }
      if (SessionId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SessionId);
      }
      if (AgentName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AgentName);
      }
      if (Metadata.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Metadata);
      }
      if (sessionState_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(SessionState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Text.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      if (MessageId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MessageId);
      }
      if (SessionId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SessionId);
      }
      if (AgentName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AgentName);
      }
      if (Metadata.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Metadata);
      }
      if (sessionState_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(SessionState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Text.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (MessageId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageId);
      }
      if (SessionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionId);
      }
      if (AgentName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AgentName);
      }
      if (Metadata.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Metadata);
      }
      if (sessionState_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SessionState);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TextMessageRequest other) {
      if (other == null) {
        return;
      }
      if (other.Text.Length != 0) {
        Text = other.Text;
      }
      if (other.MessageId.Length != 0) {
        MessageId = other.MessageId;
      }
      if (other.SessionId.Length != 0) {
        SessionId = other.SessionId;
      }
      if (other.AgentName.Length != 0) {
        AgentName = other.AgentName;
      }
      if (other.Metadata.Length != 0) {
        Metadata = other.Metadata;
      }
      if (other.sessionState_ != null) {
        if (sessionState_ == null) {
          SessionState = new global::LiveKit.Proto.AgentSessionState();
        }
        SessionState.MergeFrom(other.SessionState);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
          case 18: {
            MessageId = input.ReadString();
            break;
          }
          case 26: {
            SessionId = input.ReadString();
            break;
          }
          case 34: {
            AgentName = input.ReadString();
            break;
          }
          case 42: {
            Metadata = input.ReadString();
            break;
          }
          case 50: {
            if (sessionState_ == null) {
              SessionState = new global::LiveKit.Proto.AgentSessionState();
            }
            input.ReadMessage(SessionState);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
          case 18: {
            MessageId = input.ReadString();
            break;
          }
          case 26: {
            SessionId = input.ReadString();
            break;
          }
          case 34: {
            AgentName = input.ReadString();
            break;
          }
          case 42: {
            Metadata = input.ReadString();
            break;
          }
          case 50: {
            if (sessionState_ == null) {
              SessionState = new global::LiveKit.Proto.AgentSessionState();
            }
            input.ReadMessage(SessionState);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Response to a text message request, multiple responses may be sent for a single request until it is complete.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TextMessageResponse : pb::IMessage<TextMessageResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TextMessageResponse> _parser = new pb::MessageParser<TextMessageResponse>(() => new TextMessageResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TextMessageResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LiveKit.Proto.LivekitAgentTextReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextMessageResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextMessageResponse(TextMessageResponse other) : this() {
      messageId_ = other.messageId_;
      sessionId_ = other.sessionId_;
      switch (other.EventCase) {
        case EventOneofCase.Message:
          Message = other.Message.Clone();
          break;
        case EventOneofCase.FunctionCall:
          FunctionCall = other.FunctionCall.Clone();
          break;
        case EventOneofCase.FunctionCallOutput:
          FunctionCallOutput = other.FunctionCallOutput.Clone();
          break;
        case EventOneofCase.AgentHandoff:
          AgentHandoff = other.AgentHandoff.Clone();
          break;
        case EventOneofCase.Complete:
          Complete = other.Complete.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextMessageResponse Clone() {
      return new TextMessageResponse(this);
    }

    /// <summary>Field number for the "message_id" field.</summary>
    public const int MessageIdFieldNumber = 1;
    private string messageId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MessageId {
      get { return messageId_; }
      set {
        messageId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "session_id" field.</summary>
    public const int SessionIdFieldNumber = 2;
    private string sessionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SessionId {
      get { return sessionId_; }
      set {
        sessionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Livekit.Agent.ChatMessage Message {
      get { return eventCase_ == EventOneofCase.Message ? (global::Livekit.Agent.ChatMessage) event_ : null; }
      set {
        event_ = value;
        eventCase_ = value == null ? EventOneofCase.None : EventOneofCase.Message;
      }
    }

    /// <summary>Field number for the "function_call" field.</summary>
    public const int FunctionCallFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Livekit.Agent.FunctionCall FunctionCall {
      get { return eventCase_ == EventOneofCase.FunctionCall ? (global::Livekit.Agent.FunctionCall) event_ : null; }
      set {
        event_ = value;
        eventCase_ = value == null ? EventOneofCase.None : EventOneofCase.FunctionCall;
      }
    }

    /// <summary>Field number for the "function_call_output" field.</summary>
    public const int FunctionCallOutputFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Livekit.Agent.FunctionCallOutput FunctionCallOutput {
      get { return eventCase_ == EventOneofCase.FunctionCallOutput ? (global::Livekit.Agent.FunctionCallOutput) event_ : null; }
      set {
        event_ = value;
        eventCase_ = value == null ? EventOneofCase.None : EventOneofCase.FunctionCallOutput;
      }
    }

    /// <summary>Field number for the "agent_handoff" field.</summary>
    public const int AgentHandoffFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Livekit.Agent.AgentHandoff AgentHandoff {
      get { return eventCase_ == EventOneofCase.AgentHandoff ? (global::Livekit.Agent.AgentHandoff) event_ : null; }
      set {
        event_ = value;
        eventCase_ = value == null ? EventOneofCase.None : EventOneofCase.AgentHandoff;
      }
    }

    /// <summary>Field number for the "complete" field.</summary>
    public const int CompleteFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LiveKit.Proto.TextMessageComplete Complete {
      get { return eventCase_ == EventOneofCase.Complete ? (global::LiveKit.Proto.TextMessageComplete) event_ : null; }
      set {
        event_ = value;
        eventCase_ = value == null ? EventOneofCase.None : EventOneofCase.Complete;
      }
    }

    private object event_;
    /// <summary>Enum of possible cases for the "event" oneof.</summary>
    public enum EventOneofCase {
      None = 0,
      Message = 3,
      FunctionCall = 4,
      FunctionCallOutput = 5,
      AgentHandoff = 6,
      Complete = 7,
    }
    private EventOneofCase eventCase_ = EventOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventOneofCase EventCase {
      get { return eventCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEvent() {
      eventCase_ = EventOneofCase.None;
      event_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TextMessageResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TextMessageResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageId != other.MessageId) return false;
      if (SessionId != other.SessionId) return false;
      if (!object.Equals(Message, other.Message)) return false;
      if (!object.Equals(FunctionCall, other.FunctionCall)) return false;
      if (!object.Equals(FunctionCallOutput, other.FunctionCallOutput)) return false;
      if (!object.Equals(AgentHandoff, other.AgentHandoff)) return false;
      if (!object.Equals(Complete, other.Complete)) return false;
      if (EventCase != other.EventCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageId.Length != 0) hash ^= MessageId.GetHashCode();
      if (SessionId.Length != 0) hash ^= SessionId.GetHashCode();
      if (eventCase_ == EventOneofCase.Message) hash ^= Message.GetHashCode();
      if (eventCase_ == EventOneofCase.FunctionCall) hash ^= FunctionCall.GetHashCode();
      if (eventCase_ == EventOneofCase.FunctionCallOutput) hash ^= FunctionCallOutput.GetHashCode();
      if (eventCase_ == EventOneofCase.AgentHandoff) hash ^= AgentHandoff.GetHashCode();
      if (eventCase_ == EventOneofCase.Complete) hash ^= Complete.GetHashCode();
      hash ^= (int) eventCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MessageId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MessageId);
      }
      if (SessionId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SessionId);
      }
      if (eventCase_ == EventOneofCase.Message) {
        output.WriteRawTag(26);
        output.WriteMessage(Message);
      }
      if (eventCase_ == EventOneofCase.FunctionCall) {
        output.WriteRawTag(34);
        output.WriteMessage(FunctionCall);
      }
      if (eventCase_ == EventOneofCase.FunctionCallOutput) {
        output.WriteRawTag(42);
        output.WriteMessage(FunctionCallOutput);
      }
      if (eventCase_ == EventOneofCase.AgentHandoff) {
        output.WriteRawTag(50);
        output.WriteMessage(AgentHandoff);
      }
      if (eventCase_ == EventOneofCase.Complete) {
        output.WriteRawTag(58);
        output.WriteMessage(Complete);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MessageId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MessageId);
      }
      if (SessionId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SessionId);
      }
      if (eventCase_ == EventOneofCase.Message) {
        output.WriteRawTag(26);
        output.WriteMessage(Message);
      }
      if (eventCase_ == EventOneofCase.FunctionCall) {
        output.WriteRawTag(34);
        output.WriteMessage(FunctionCall);
      }
      if (eventCase_ == EventOneofCase.FunctionCallOutput) {
        output.WriteRawTag(42);
        output.WriteMessage(FunctionCallOutput);
      }
      if (eventCase_ == EventOneofCase.AgentHandoff) {
        output.WriteRawTag(50);
        output.WriteMessage(AgentHandoff);
      }
      if (eventCase_ == EventOneofCase.Complete) {
        output.WriteRawTag(58);
        output.WriteMessage(Complete);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MessageId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageId);
      }
      if (SessionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionId);
      }
      if (eventCase_ == EventOneofCase.Message) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Message);
      }
      if (eventCase_ == EventOneofCase.FunctionCall) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FunctionCall);
      }
      if (eventCase_ == EventOneofCase.FunctionCallOutput) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FunctionCallOutput);
      }
      if (eventCase_ == EventOneofCase.AgentHandoff) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AgentHandoff);
      }
      if (eventCase_ == EventOneofCase.Complete) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Complete);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TextMessageResponse other) {
      if (other == null) {
        return;
      }
      if (other.MessageId.Length != 0) {
        MessageId = other.MessageId;
      }
      if (other.SessionId.Length != 0) {
        SessionId = other.SessionId;
      }
      switch (other.EventCase) {
        case EventOneofCase.Message:
          if (Message == null) {
            Message = new global::Livekit.Agent.ChatMessage();
          }
          Message.MergeFrom(other.Message);
          break;
        case EventOneofCase.FunctionCall:
          if (FunctionCall == null) {
            FunctionCall = new global::Livekit.Agent.FunctionCall();
          }
          FunctionCall.MergeFrom(other.FunctionCall);
          break;
        case EventOneofCase.FunctionCallOutput:
          if (FunctionCallOutput == null) {
            FunctionCallOutput = new global::Livekit.Agent.FunctionCallOutput();
          }
          FunctionCallOutput.MergeFrom(other.FunctionCallOutput);
          break;
        case EventOneofCase.AgentHandoff:
          if (AgentHandoff == null) {
            AgentHandoff = new global::Livekit.Agent.AgentHandoff();
          }
          AgentHandoff.MergeFrom(other.AgentHandoff);
          break;
        case EventOneofCase.Complete:
          if (Complete == null) {
            Complete = new global::LiveKit.Proto.TextMessageComplete();
          }
          Complete.MergeFrom(other.Complete);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MessageId = input.ReadString();
            break;
          }
          case 18: {
            SessionId = input.ReadString();
            break;
          }
          case 26: {
            global::Livekit.Agent.ChatMessage subBuilder = new global::Livekit.Agent.ChatMessage();
            if (eventCase_ == EventOneofCase.Message) {
              subBuilder.MergeFrom(Message);
            }
            input.ReadMessage(subBuilder);
            Message = subBuilder;
            break;
          }
          case 34: {
            global::Livekit.Agent.FunctionCall subBuilder = new global::Livekit.Agent.FunctionCall();
            if (eventCase_ == EventOneofCase.FunctionCall) {
              subBuilder.MergeFrom(FunctionCall);
            }
            input.ReadMessage(subBuilder);
            FunctionCall = subBuilder;
            break;
          }
          case 42: {
            global::Livekit.Agent.FunctionCallOutput subBuilder = new global::Livekit.Agent.FunctionCallOutput();
            if (eventCase_ == EventOneofCase.FunctionCallOutput) {
              subBuilder.MergeFrom(FunctionCallOutput);
            }
            input.ReadMessage(subBuilder);
            FunctionCallOutput = subBuilder;
            break;
          }
          case 50: {
            global::Livekit.Agent.AgentHandoff subBuilder = new global::Livekit.Agent.AgentHandoff();
            if (eventCase_ == EventOneofCase.AgentHandoff) {
              subBuilder.MergeFrom(AgentHandoff);
            }
            input.ReadMessage(subBuilder);
            AgentHandoff = subBuilder;
            break;
          }
          case 58: {
            global::LiveKit.Proto.TextMessageComplete subBuilder = new global::LiveKit.Proto.TextMessageComplete();
            if (eventCase_ == EventOneofCase.Complete) {
              subBuilder.MergeFrom(Complete);
            }
            input.ReadMessage(subBuilder);
            Complete = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MessageId = input.ReadString();
            break;
          }
          case 18: {
            SessionId = input.ReadString();
            break;
          }
          case 26: {
            global::Livekit.Agent.ChatMessage subBuilder = new global::Livekit.Agent.ChatMessage();
            if (eventCase_ == EventOneofCase.Message) {
              subBuilder.MergeFrom(Message);
            }
            input.ReadMessage(subBuilder);
            Message = subBuilder;
            break;
          }
          case 34: {
            global::Livekit.Agent.FunctionCall subBuilder = new global::Livekit.Agent.FunctionCall();
            if (eventCase_ == EventOneofCase.FunctionCall) {
              subBuilder.MergeFrom(FunctionCall);
            }
            input.ReadMessage(subBuilder);
            FunctionCall = subBuilder;
            break;
          }
          case 42: {
            global::Livekit.Agent.FunctionCallOutput subBuilder = new global::Livekit.Agent.FunctionCallOutput();
            if (eventCase_ == EventOneofCase.FunctionCallOutput) {
              subBuilder.MergeFrom(FunctionCallOutput);
            }
            input.ReadMessage(subBuilder);
            FunctionCallOutput = subBuilder;
            break;
          }
          case 50: {
            global::Livekit.Agent.AgentHandoff subBuilder = new global::Livekit.Agent.AgentHandoff();
            if (eventCase_ == EventOneofCase.AgentHandoff) {
              subBuilder.MergeFrom(AgentHandoff);
            }
            input.ReadMessage(subBuilder);
            AgentHandoff = subBuilder;
            break;
          }
          case 58: {
            global::LiveKit.Proto.TextMessageComplete subBuilder = new global::LiveKit.Proto.TextMessageComplete();
            if (eventCase_ == EventOneofCase.Complete) {
              subBuilder.MergeFrom(Complete);
            }
            input.ReadMessage(subBuilder);
            Complete = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Indicates the text message session is complete.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TextMessageComplete : pb::IMessage<TextMessageComplete>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TextMessageComplete> _parser = new pb::MessageParser<TextMessageComplete>(() => new TextMessageComplete());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TextMessageComplete> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LiveKit.Proto.LivekitAgentTextReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextMessageComplete() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextMessageComplete(TextMessageComplete other) : this() {
      switch (other.ResultCase) {
        case ResultOneofCase.SessionState:
          SessionState = other.SessionState.Clone();
          break;
        case ResultOneofCase.Error:
          Error = other.Error.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextMessageComplete Clone() {
      return new TextMessageComplete(this);
    }

    /// <summary>Field number for the "session_state" field.</summary>
    public const int SessionStateFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LiveKit.Proto.AgentSessionState SessionState {
      get { return resultCase_ == ResultOneofCase.SessionState ? (global::LiveKit.Proto.AgentSessionState) result_ : null; }
      set {
        result_ = value;
        resultCase_ = value == null ? ResultOneofCase.None : ResultOneofCase.SessionState;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LiveKit.Proto.TextMessageError Error {
      get { return resultCase_ == ResultOneofCase.Error ? (global::LiveKit.Proto.TextMessageError) result_ : null; }
      set {
        result_ = value;
        resultCase_ = value == null ? ResultOneofCase.None : ResultOneofCase.Error;
      }
    }

    private object result_;
    /// <summary>Enum of possible cases for the "result" oneof.</summary>
    public enum ResultOneofCase {
      None = 0,
      SessionState = 1,
      Error = 2,
    }
    private ResultOneofCase resultCase_ = ResultOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResultOneofCase ResultCase {
      get { return resultCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearResult() {
      resultCase_ = ResultOneofCase.None;
      result_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TextMessageComplete);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TextMessageComplete other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SessionState, other.SessionState)) return false;
      if (!object.Equals(Error, other.Error)) return false;
      if (ResultCase != other.ResultCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (resultCase_ == ResultOneofCase.SessionState) hash ^= SessionState.GetHashCode();
      if (resultCase_ == ResultOneofCase.Error) hash ^= Error.GetHashCode();
      hash ^= (int) resultCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (resultCase_ == ResultOneofCase.SessionState) {
        output.WriteRawTag(10);
        output.WriteMessage(SessionState);
      }
      if (resultCase_ == ResultOneofCase.Error) {
        output.WriteRawTag(18);
        output.WriteMessage(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (resultCase_ == ResultOneofCase.SessionState) {
        output.WriteRawTag(10);
        output.WriteMessage(SessionState);
      }
      if (resultCase_ == ResultOneofCase.Error) {
        output.WriteRawTag(18);
        output.WriteMessage(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (resultCase_ == ResultOneofCase.SessionState) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SessionState);
      }
      if (resultCase_ == ResultOneofCase.Error) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TextMessageComplete other) {
      if (other == null) {
        return;
      }
      switch (other.ResultCase) {
        case ResultOneofCase.SessionState:
          if (SessionState == null) {
            SessionState = new global::LiveKit.Proto.AgentSessionState();
          }
          SessionState.MergeFrom(other.SessionState);
          break;
        case ResultOneofCase.Error:
          if (Error == null) {
            Error = new global::LiveKit.Proto.TextMessageError();
          }
          Error.MergeFrom(other.Error);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::LiveKit.Proto.AgentSessionState subBuilder = new global::LiveKit.Proto.AgentSessionState();
            if (resultCase_ == ResultOneofCase.SessionState) {
              subBuilder.MergeFrom(SessionState);
            }
            input.ReadMessage(subBuilder);
            SessionState = subBuilder;
            break;
          }
          case 18: {
            global::LiveKit.Proto.TextMessageError subBuilder = new global::LiveKit.Proto.TextMessageError();
            if (resultCase_ == ResultOneofCase.Error) {
              subBuilder.MergeFrom(Error);
            }
            input.ReadMessage(subBuilder);
            Error = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::LiveKit.Proto.AgentSessionState subBuilder = new global::LiveKit.Proto.AgentSessionState();
            if (resultCase_ == ResultOneofCase.SessionState) {
              subBuilder.MergeFrom(SessionState);
            }
            input.ReadMessage(subBuilder);
            SessionState = subBuilder;
            break;
          }
          case 18: {
            global::LiveKit.Proto.TextMessageError subBuilder = new global::LiveKit.Proto.TextMessageError();
            if (resultCase_ == ResultOneofCase.Error) {
              subBuilder.MergeFrom(Error);
            }
            input.ReadMessage(subBuilder);
            Error = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AgentSessionState : pb::IMessage<AgentSessionState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AgentSessionState> _parser = new pb::MessageParser<AgentSessionState>(() => new AgentSessionState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AgentSessionState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LiveKit.Proto.LivekitAgentTextReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentSessionState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentSessionState(AgentSessionState other) : this() {
      version_ = other.version_;
      switch (other.DataCase) {
        case DataOneofCase.Snapshot:
          Snapshot = other.Snapshot;
          break;
        case DataOneofCase.Delta:
          Delta = other.Delta;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentSessionState Clone() {
      return new AgentSessionState(this);
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 1;
    private ulong version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    /// <summary>Field number for the "snapshot" field.</summary>
    public const int SnapshotFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Snapshot {
      get { return HasSnapshot ? (pb::ByteString) data_ : pb::ByteString.Empty; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        dataCase_ = DataOneofCase.Snapshot;
      }
    }
    /// <summary>Gets whether the "snapshot" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSnapshot {
      get { return dataCase_ == DataOneofCase.Snapshot; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "snapshot" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSnapshot() {
      if (HasSnapshot) {
        ClearData();
      }
    }

    /// <summary>Field number for the "delta" field.</summary>
    public const int DeltaFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Delta {
      get { return HasDelta ? (pb::ByteString) data_ : pb::ByteString.Empty; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        dataCase_ = DataOneofCase.Delta;
      }
    }
    /// <summary>Gets whether the "delta" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDelta {
      get { return dataCase_ == DataOneofCase.Delta; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "delta" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDelta() {
      if (HasDelta) {
        ClearData();
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      Snapshot = 2,
      Delta = 3,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AgentSessionState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AgentSessionState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Version != other.Version) return false;
      if (Snapshot != other.Snapshot) return false;
      if (Delta != other.Delta) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Version != 0UL) hash ^= Version.GetHashCode();
      if (HasSnapshot) hash ^= Snapshot.GetHashCode();
      if (HasDelta) hash ^= Delta.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Version != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Version);
      }
      if (HasSnapshot) {
        output.WriteRawTag(18);
        output.WriteBytes(Snapshot);
      }
      if (HasDelta) {
        output.WriteRawTag(26);
        output.WriteBytes(Delta);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Version != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Version);
      }
      if (HasSnapshot) {
        output.WriteRawTag(18);
        output.WriteBytes(Snapshot);
      }
      if (HasDelta) {
        output.WriteRawTag(26);
        output.WriteBytes(Delta);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Version != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Version);
      }
      if (HasSnapshot) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Snapshot);
      }
      if (HasDelta) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Delta);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AgentSessionState other) {
      if (other == null) {
        return;
      }
      if (other.Version != 0UL) {
        Version = other.Version;
      }
      switch (other.DataCase) {
        case DataOneofCase.Snapshot:
          Snapshot = other.Snapshot;
          break;
        case DataOneofCase.Delta:
          Delta = other.Delta;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Version = input.ReadUInt64();
            break;
          }
          case 18: {
            Snapshot = input.ReadBytes();
            break;
          }
          case 26: {
            Delta = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Version = input.ReadUInt64();
            break;
          }
          case 18: {
            Snapshot = input.ReadBytes();
            break;
          }
          case 26: {
            Delta = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TextMessageError : pb::IMessage<TextMessageError>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TextMessageError> _parser = new pb::MessageParser<TextMessageError>(() => new TextMessageError());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TextMessageError> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LiveKit.Proto.LivekitAgentTextReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextMessageError() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextMessageError(TextMessageError other) : this() {
      message_ = other.message_;
      code_ = other.code_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextMessageError Clone() {
      return new TextMessageError(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 2;
    private global::LiveKit.Proto.TextMessageErrorCode code_ = global::LiveKit.Proto.TextMessageErrorCode.InternalError;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LiveKit.Proto.TextMessageErrorCode Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TextMessageError);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TextMessageError other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Message != other.Message) return false;
      if (Code != other.Code) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (Code != global::LiveKit.Proto.TextMessageErrorCode.InternalError) hash ^= Code.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (Code != global::LiveKit.Proto.TextMessageErrorCode.InternalError) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Code);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (Code != global::LiveKit.Proto.TextMessageErrorCode.InternalError) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Code);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Code != global::LiveKit.Proto.TextMessageErrorCode.InternalError) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Code);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TextMessageError other) {
      if (other == null) {
        return;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.Code != global::LiveKit.Proto.TextMessageErrorCode.InternalError) {
        Code = other.Code;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
          case 16: {
            Code = (global::LiveKit.Proto.TextMessageErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
          case 16: {
            Code = (global::LiveKit.Proto.TextMessageErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
